site_name: ToDo App Documentation

nav:
  - Home: index.md
  - App: main.md
  - DB Methods: db.md
  - Models: models.md
  - Utils Methods: utils.md
  - Tests: 
    - Conftest: conftest.md
    - Unit tests: unit_tests.md
    - Integration tests: integration_tests.md
    - E2E tests: e2e_tests.md
    - Load tests: load_tests.md
theme: 
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      primary: purple
      accent: purple

extra: 
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/VictoriaPerez17/todo_app_perezayon

markdown_extensions: 
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list

plugins: 
  - mkdocstrings


copyright: |
  &copy: 2024 <a href="https://github.com/VictoriaPerez17" target="_blank" rel="noopener">Pérez Ayon</a>