name: Publish docs via GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_DB: tests_todo
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: Victoria17
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout main
        uses: actions/checkout@v2

      - name: Deploy docs
        uses: mhausenblas/mkdocs-deploy-gh-pages@master

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CONFIG_FILE: /home/runner/work/todo_app_perezayon/todo_app_perezayon/mkdocs.yml
          EXTRA_PACKAGES: build-base
          REQUIREMENTS: /home/runner/work/todo_app_perezayon/todo_app_perezayon/requirements.txt