name: Publish docs via GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          DATABASE: tests_todo
          HOST: localhost
          USER: postgres
          PASSWORD: Victoria17
          PORT: 5432
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout main
        uses: actions/checkout@v2

      - name: Install MariaDB connector
        run: |
          wget https://dlm.mariadb.com/3964806/Connectors/c/connector-c-3.4.3/mariadb-connector-c-3.4.3-ubuntu-noble-amd64.tar.gz 
          tar -xzf mariadb-connector-c-3.4.3-ubuntu-noble-amd64.tar.gz
          cd mariadb-connector-c-3.4.3-ubuntu-noble-amd64
          echo "MARIADB_CONFIG=$(pwd)/bin/" >> $GITHUB_ENV
          chmod -R 755 bin

      - name: Check MARIADB variable
        run: |
          echo "MARIADB_CONFIG = $MARIADB_CONFIG"
          sudo apt-get install -y libmariadb-dev

      - name: Deploy docs
        uses: mhausenblas/mkdocs-deploy-gh-pages@master


        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CONFIG_FILE: folder/mkdocs.yml
          EXTRA_PACKAGES: build-base
          REQUIREMENTS: folder/requirements.txt