name: ToDo app tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mariadb:
        image: mariadb:latest
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: Victoria17
          MYSQL_DATABASE: new_todo_list
          MYSQL_USER: root
          MYSQL_PASSWORD: Victoria17

    steps:
      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10.11'

      - name: Add PYTHONPATH
        run: |
          echo "Setting PYTHONPATH"
          echo "PYTHONPATH=$(pwd)" >> $GITHUB_ENV

      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Run tests
        run: |
          echo "PYTHONPATH in this step: $PYTHONPATH"  # This should show the updated PYTHONPATH
          pytest
