name: ToDo app tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mariadb:
        image: mariadb:latest
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: test_user
          MYSQL_DATABASE: test_todo_list
          MYSQL_USER: test_user
          MYSQL_PASSWORD: test_password

    steps:
      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10.11'

      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Add project to PYTHONPATH
        run: |
          export PYTHONPATH=$(/home/runner/work/todo_app_perezayon/todo_app_perezayon)

      - name: Run tests
        run: |
          pytest