name: ToDo app tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mariadb:
        image: mariadb:latest
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: Victoria17
          MYSQL_DATABASE: new_todo_list
          MYSQL_USER: root
          MYSQL_PASSWORD: Victoria17

    steps:
      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10.11'

      - name: Install MariaDB connector
        run: |
          mkdir maria_db_conn
          cd maria_db_conn
          wget https://dlm.mariadb.com/3964806/Connectors/c/connector-c-3.4.3/mariadb-connector-c-3.4.3-ubuntu-noble-amd64.tar.gz 
          tar -xzf mariadb-connector-c-3.4.3-ubuntu-noble-amd64.tar.gz
          cd mariadb-connector-c-3.4.3-ubuntu-noble-amd64
          ls
          echo "-------------"
          ls lib/
          echo "-------------"
          ls lib/mariadb/
          sudo install lib/mariadb/libmaodb.so /usr/lib/
          sudo install -d /usr/lib/mariadb/
          sudo install -d /usr/lib/mariadb/plugin/
          sudo install lib/mariadb/plugin/auth_gssapi_client.so /usr/lib/mariadb/plugin/
          sudo install lib/mariadb/plugin/caching_sha2_password.so /usr/lib/mariadb/plugin/
          sudo install lib/mariadb/plugin/client_ed25519.so /usr/lib/mariadb/plugin/
          sudo install lib/mariadb/plugin/dialog.so /usr/lib/mariadb/plugin/
          sudo install lib/mariadb/plugin/mysql_clear_password.so /usr/lib/mariadb/plugin/
          sudo install lib/mariadb/plugin/sha256_password.so /usr/lib/mariadb/plugin/

      - name: Add PYTHONPATH
        run: |
          sudo apt-get install -y libmariadb-dev
          echo "PYTHONPATH=$(pwd)/app/src" >> $GITHUB_ENV

      - name: Install requirements
        run: |
          sudo apt-get remove python3-blinker
          sudo python -m pip install --upgrade pip
          sudo python -m pip install -r requirements.txt

      - name: Set up ChromeDriver
        uses: nanasess/setup-chromedriver@v2
        with:
          chromedriver-version: '88.0.4324.96'
          chromeapp: chrome

      - name: Set up Xvfb and run ChromeDriver
        run: |
          export DISPLAY=:99
          chromedriver --url-base=/wd/hub &  # Start ChromeDriver in background
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # Start Xvfb (virtual display)

      - name: Run tests
        run: |
          pytest app/tests/unit/
          pytest app/tests/integration/
