name: ToDo app tests

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mariadb:
        image: mariadb:latest
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: Victoria17
          MYSQL_DATABASE: new_todo_list
          MYSQL_USER: root
          MYSQL_PASSWORD: Victoria17

    steps:
      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10.11'

      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Run tests
        run: |
          echo "PYTHONPATH=/home/runner/work/todo_app_perezayon/todo_app_perezayon" >> $GITHUB_ENV
          echo "PYTHONPATH=$PYTHONPATH"
          pytest
